config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post    '/comment',       to: 'comments#create'
  post    '/vote',          to: 'votes#create'
  delete  '/unvote',        to: 'votes#destroy'
  get     '/read_article',  to: 'articles#show'
  post    '/read_article',  to: 'articles#show'
  get     '/articles',      to: 'articles#index'
  post    '/articles',      to: 'articles#index'
  get     '/new_article',   to: 'articles#new'
  post    '/new_article',   to: 'articles#create'
  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'
  get     '/signin',        to: 'sessions#new'
  post    '/signin',        to: 'sessions#create'
  delete  '/signout',       to: 'sessions#destroy'
  root to: 'pages#homepage'
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :author, class_name: 'User'
  has_many :votes
  has_many :article_categories
  has_many :comments
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { maximum: 50 }
  validates :text, presence: true, length: { maximum: 600 }
  validates :image, presence: true

  def self.most_voted
    # Article.eager_load(:votes).group("votes.article_id").count(:votes).first
    Article.select('articles.*, COUNT(votes.id) as voted')
      .joins('FULL OUTER JOIN votes ON votes.article_id = articles.id').group('articles.id')
      .order(voted: :desc).first
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    redirect_to signin_path unless logged_in?
    @article = Article.new
    @new_article_link = 'nav-link-active'
  end

  def create
    @article = current_user.created_articles.build(article_params)
    if params[:article][:categories].nil?
      @article.errors.add(:Categories, " can't be empty")
      render 'new'
      nil
    elsif @article.save
      params[:article][:categories].each do |catego|
        @article_category = ArticleCategory.new(article: @article, category: Category.find(catego.to_i))
        @article_category.save
      end
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @all_article_link = 'nav-link-active'
    giveme_articles_per_categorie(params[:id])
  end

  def show
    @show_article = ArticleCategory.get_article(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image, :author_id)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def giveme_articles_per_categorie(category_id)
    @articles_per_categorie = ArticleCategory.articles_of_categorie(category_id)
  end
end

app/views/articles/index.html.erb
<% @articlous %>
<div class="index-container">
  <% @articles_per_categorie.each_with_index do |art, index| %>
    <% if index == 0 || index == 1%>
      <div class="one" style="background-image: url(<%= art.article.image %>)">
      </div>
      <div class="two">
      <div class="like-container"> 
          <%= pluralize(art.article.votes.length, 'Like') %>
          <% if logged_in?%>
            <% if art.article.votes.any? { |x| x.user_id == current_user.id} %>
              <%= link_to unvote_path(:id => art.article.id, :category_id => art.category.id), class: "give_dislike", method: :delete   do %>
                <%= material_icon.thumb_up %>
              <% end %>
            <% else %>
              <%= link_to vote_path(:id => art.article.id, :category_id => art.category.id), class: "give_like", method: :post   do %>
                <%= material_icon.thumb_up %>
              <% end %>
            <% end %>
          <% end %>
      </div>
        <h3><%= art.article.title%></h3>
        <h1>By <%= art.article.author.name %></h1>
        <p><%= art.article.text.truncate(250, separator: ' ') %></p>
        <%= link_to 'Read more', read_article_path(:id => art.article.id), class: "read-more", method: :post %>
      </div>
    <% else %>
      <div class="two">
        <div class="like-container"> 
          <%= pluralize(art.article.votes.length, 'Like') %>
          <% if logged_in? %>
            <% if art.article.votes.any? { |x| x.user_id == current_user.id} %>
              <%= link_to unvote_path(:id => art.article.id, :category_id => art.category.id), class: "give_dislike", method: :delete   do %>
                <%= material_icon.thumb_up %>
              <% end %>
            <% else %>
              <%= link_to vote_path(:id => art.article.id, :category_id => art.category.id), class: "give_like", method: :post   do %>
                <%= material_icon.thumb_up %>
              <% end %>
            <% end %>
          <% end %>
        </div>
        <h3><%= art.article.title%></h3>
        <h1>By <%= art.article.author.name %></h1>
        <p><%= art.article.text.truncate(250, separator: ' ') %></p>
        <%= link_to 'Read more', read_article_path(:id => art.article.id), class: "read-more", method: :post %>
      </div>
      <div class="one" style="background-image: url(<%= art.article.image %>)">
      </div>
    <% end %>
  <% end %>
</div>
<%= render 'layouts/footer'%>

app/views/articles/new.html.erb
<div class="new_article_container">
  <%= form_for @article, url: new_article_path do |f| %>
  <div>
    <% if @article.errors.any?%>
      <% @article.errors.full_messages.each do |error|%>
        <p> <%= error %> </p>
      <% end %>
    <% end %>
  </div>
    <%= f.label :title %>
    <%= f.text_field :title, :autofocus => true %>
    <%= f.label :content %>
    <%= f.text_area :text %>
    <%= f.label :categories%>
    <%= f.select(:categories, all_categories.collect { |c| [c.name, c.id] },
               {:include_blank => false,
               :include_hidden => false},
               { class: 'chosen-select', multiple: true}) %>
    <%= f.label :image %>
    <%= f.file_field :image %>
    <%= f.submit 'Create article' %>
  <% end %>
</div>

<script>
$('.chosen-select').chosen(
  {multiple: true,
  placeholder_text_multiple: 'Select category(s)'}
)
</script>

app/views/articles/show.html.erb
<div class="container-show-article">
<% @art = @show_article[0] %>
  <% @article_id = @art.article.id%>
  <h1><%= @art.article.title %></h1>
  <%= cl_image_tag(@art.article.image)%>
  <p><%= @art.article.text %><p>
  <h4 class="article_info">By <%= @art.article.author.name %></h4>
  <h4 class="article_info"><%= @art.article.created_at%></h4>
  <hr>
  <div class="create-comment-container">
    <% if logged_in? %>
      <%= form_for :comments, :url => comment_path(:article_id => @article_id) do |f| %>
        <%= f.label :Comment_something!%>
        <%= f.text_area :text %>
        <%= f.submit 'Leave comment'%>
      <% end %>
    <% else %>
      <%= link_to 'Login to comment', signin_path, class: 'orange-link' %>
    <% end %>
    <div class="comments-article">
    <% if @art.article.comments.size>0 %>
      <% @art.article.comments.reverse.each do |x| %>
        <div>
          <h2><%= x.user.name %></h2>
          <p><%= x.text %></p>
        </div>
      <%end%>
    <% else %>
      <h2 class="no-comment">No comments so far, be the first!<h2>
    <% end %>
    </div>
  </div>
</div>