config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  post    '/comment',       to: 'comments#create'
  post    '/vote',          to: 'votes#create'
  delete  '/unvote',        to: 'votes#destroy'
  get     '/read_article',  to: 'articles#show'
  post    '/read_article',  to: 'articles#show'
  get     '/articles',      to: 'articles#index'
  post    '/articles',      to: 'articles#index'
  get     '/new_article',   to: 'articles#new'
  post    '/new_article',   to: 'articles#create'
  get     '/signup',        to: 'users#new'
  post    '/signup',        to: 'users#create'
  get     '/signin',        to: 'sessions#new'
  post    '/signin',        to: 'sessions#create'
  delete  '/signout',       to: 'sessions#destroy'
  root to: 'pages#homepage'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :author, class_name: 'User'
  has_many :votes
  has_many :article_categories
  has_many :comments
  has_many :categories, through: :article_categories
  validates :title, presence: true, length: { maximum: 50 }
  validates :text, presence: true, length: { maximum: 600 }
  validates :image, presence: true

  def self.most_voted
    # Article.eager_load(:votes).group("votes.article_id").count(:votes).first
    Article.select('articles.*, COUNT(votes.id) as voted')
      .joins('FULL OUTER JOIN votes ON votes.article_id = articles.id').group('articles.id')
      .order(voted: :desc).first
  end
end

app/models/article_category.rb
class ArticleCategory < ApplicationRecord
  belongs_to :article, class_name: :Article
  belongs_to :category, class_name: :Category

  def self.five_most_recent_articles
    ArticleCategory.where('"article_categories"."id" IN
                          (SELECT "f"."id" FROM "article_categories" "f"
                            INNER JOIN (SELECT MAX("c"."id") as "id"
                            FROM "article_categories" as "c"
                            INNER JOIN
                            (SELECT MIN("x"."id") as "id", "x"."article_id"
                              FROM "article_categories" as "x"
                              GROUP BY "x"."article_id") "d" ON "c"."id" = "d"."id"
                            GROUP BY "c"."category_id"
                            ) "s"
                          ON "f"."id" = "s"."id"
                          ORDER BY "f"."created_at" DESC LIMIT(5))')
      .order('"article_categories"."category_id" ASC')
      .eager_load(:article, :category)
  end

  def self.articles_of_categorie(id)
    ArticleCategory.where('article_categories.category_id = ?', id)
      .order(created_at: :desc)
      .limit(4)
      .eager_load({ article: [:author, { votes: :user }] }, :category)
  end

  def self.cat_with_art
    ArticleCategory.includes(:category).select('DISTINCT "article_categories"."category_id"').order(category_id: :asc)
  end

  def self.get_article(article_id)
    ArticleCategory.where('"article_categories"."article_id" = ?', article_id)
      .eager_load({ article: [:author, { votes: :user }, { comments: :user }] }, :category)
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories, foreign_key: :category_id
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :created_articles, foreign_key: :author_id, class_name: 'Article'
  has_many :votes, class_name: 'Vote'
  has_many :comments
  validates :name, presence: true, length: { in: 2..15 }
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :article
  belongs_to :user

  def self.voted?(user_id, article_id)
    Vote.where('user_id = ? AND article_id = ?', user_id, article_id)
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def new
    redirect_to signin_path unless logged_in?
    @article = Article.new
    @new_article_link = 'nav-link-active'
  end

  def create
    @article = current_user.created_articles.build(article_params)
    if params[:article][:categories].nil?
      @article.errors.add(:Categories, " can't be empty")
      render 'new'
      nil
    elsif @article.save
      params[:article][:categories].each do |catego|
        @article_category = ArticleCategory.new(article: @article, category: Category.find(catego.to_i))
        @article_category.save
      end
      redirect_to root_path
    else
      render 'new'
    end
  end

  def index
    @all_article_link = 'nav-link-active'
    giveme_articles_per_categorie(params[:id])
  end

  def show
    @show_article = ArticleCategory.get_article(params[:id])
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :image, :author_id)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article_id = params[:article_id]
    params[:comments][:user_id] = current_user.id
    params[:comments][:article_id] = @article_id
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to read_article_path(id: @article_id)
    else
      render "article?id=#{@article_id}"
    end
  end

  private

  def comment_params
    params.require(:comments).permit(:text, :user_id, :article_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def homepage
    @home_link = 'nav-link-active'
    @article_categories = ArticleCategory.five_most_recent_articles
    @main_article = Article.most_voted
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @signin_link = 'nav-link-active'
    redirect_to root_path if logged_in?
  end

  def create
    @user = User.find_by(name: params[:session][:name])
    if @user
      log_in(@user)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to signin_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    redirect_to root_path if logged_in?
    @user = User.new
    @signup_link = 'nav-link-active'
  end

  def create
    @user = User.new(user_params)
    binding.pry
    if @user.save
      log_in(@user)
      redirect_to root_path
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    article_id = params[:id]
    user_id = current_user.id
    @new_vote = Vote.new(user_id: user_id, article_id: article_id)
    @new_vote.save
    giveme_articles_per_categorie(params[:category_id])
    redirect_to articles_path(id: params[:category_id])
  end

  def destroy
    article_id = params[:id]
    user_id = current_user.id
    article_voted = Vote.where('user_id = ? AND article_id = ?', user_id, article_id)
    article_voted.destroy_all
    giveme_articles_per_categorie(params[:category_id])
    redirect_to articles_path(id: params[:category_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def giveme_articles_per_categorie(category_id)
    @articles_per_categorie = ArticleCategory.articles_of_categorie(category_id)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    cookies.signed[:user_id] = user.id
    @current_user = user
  end

  def log_out
    cookies.delete(:user_id)
    @current_user = nil
  end

  def current_user=(user)
    @current_user = user
  end

  def logged_in?
    !current_user.nil?
  end

  def current_user
    @current_user ||= User.find_by(id: cookies.signed[:user_id])
  end

  def all_categories
    Category.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
  def voted?(article_id)
    !Vote.voted?(@current_user, article_id).nil?
  end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
<div class='footer-div-logo'>
    <%= link_to root_path do %>
      <%= image_tag 'logo.png' %>
    <% end %>
  </div>
  <div class='footer-div-links'>
    <ul>
      <li><%= link_to "Privacy Policy", root_path %></li>
      <li><%= link_to "Terms & Conditions", root_path %></li>
      <li>Copyright 2014. All rights reserved.</li>
    <ul>
  </div>
  <div class='footer-div-user'>
    <span>Connect with us:</span>
    <%= link_to root_path do %>
      <%= image_tag 'twitter.svg' %>
    <% end %>
    <%= link_to root_path do %>
      <%= image_tag 'instagram.svg' %>
    <% end %>
    <%= link_to root_path do %>
      <%= image_tag 'facebook.svg' %>
    <% end %>
  </div>
</div>
</footer>

app/views/layouts/_header.html.erb
<nav class='nav'>
  <div class='nav-div-logo'>
    <%= link_to root_path, class:'darken-4 btn-flat' do %>
    <%= image_tag 'logo.png' %>
    <% end %>
  </div>
  <div class='nav-div-links'>
    <ul>
      <li><%= link_to "HOME", root_path, class: "#{ @home_link }" %></li>
      <li>
        <div class="categories_dropdown">
          <a>CATEGORIES &#8595;</a>
          <div class="categories_dropdown_content">
          <% @categorie_list.each do |x|%>
            <%= link_to x.category.name, articles_path(:id => x.category.id), method: :post%>
          <% end %>
          </div>
        </div></li>
      <% if logged_in? %>
        <li><%= link_to "NEW ARTICLE", new_article_path, class: "#{ @new_article_link }" %></li>
      <% end %>
    <ul>
  </div>
  <div class='nav-div-user'>
  <% if logged_in? %>
    <%= link_to "Sign out", signout_path, method: :delete %>
  <% else %>
    <%= link_to "LOGIN", signin_path, class: "#{ @signin_link }" %>
    &nbsp;|&nbsp;
    <%= link_to "REGISTER", signup_path, class: "#{ @signup_link }" %>
  <% end %>
  </div>
</nav>

app/views/layouts/_no.html.erb
<div style="background-image: url(kmd)">
      <h4>No data</h4>
      <h6>No data</h6>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MangaTop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': Rails.env.production? ? "reload" : "" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": Rails.env.production? ? "reload" : "" %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_importmap_tags %>
  </head>

  <body data-controller="livereload">
    <%= render 'layouts/header' %>
    <%= yield %>
  </body>
</html>

app/views/pages/homepage.html.erb
<div class="homepage-layout">
<% if @main_article != nil %>
    <%= link_to signin_path, class: "homepage-featured" do %>
      <div style="background-image: url('<%= @main_article.image.url %>')">
        <h2><%= @main_article.title %></h2>
        <h4><%= @main_article.text.truncate(120, separator: ' ') %></h4>
      </div>
    <% end %>
  <% end %>
  <% @article_categories.each_with_index do |art, index| %>
    <% class_article = 'homepage-mid' %>
    <% class_article = 'homepage-small' if index > 0 %>
      <%= link_to articles_path(:id => art.category.id), class:"#{class_article} scan-hover", method: :post do %>
        <div style="background-image: url('<%= art.article.image.url %>')">
          <h4><%= art.category.name %></h4>
          <h6><%= art.article.title %></h6>
        </div>
      <% end %>
    <% end %>
</div>